<a href="https://colab.research.google.com/github/NajmulGit/VS_Code_SQL/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

# **Median**

In [ ]:
%%sql

select netprice
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        netprice
0          98.97
1         659.78
2          54.38
3         286.69
4         135.75
...          ...
199868    139.19
199869    159.99
199870     53.67
199871    293.40
199872      6.88

[199873 rows x 1 columns]

In [ ]:
%%sql

select
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY netprice) AS median_price
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [ ]:
%%sql
select *
from sales
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64

In [ ]:
%%sql
select *
from product
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3

In [ ]:
%%sql
select
  p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN group (order by (case when
      orderdate between '2022-01-01' and '2022-12-31' then (netprice*quantity*exchangerate) end )) AS y2022_median_sales,
  PERCENTILE_CONT(0.5) WITHIN group (order by (case
    when orderdate between '2023-01-01' and '2023-12-31' then (netprice*quantity*exchangerate) end)) as y2023_median_sales

from sales s
left join product p on s.productkey = p.productkey
group by
  categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

# **Advanced Segmentation**

In [ ]:
%%sql

select *
from sales
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64

In [ ]:
%%sql

select
  orderdate,
  quantity,
  netprice,
  case
      when quantity>=2 and netprice>= 100 then 'maltiple high value order'
      when netprice>=100 then 'single high value item'
      when quantity>=2 then 'maltiple standard item'
      else 'single standard item'
  end as order_type
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       single standard item
1  2015-01-01         1    659.78     single high value item
2  2015-01-01         2     54.38     maltiple standard item
3  2015-01-01         4    286.69  maltiple high value order
4  2015-01-01         7    135.75  maltiple high value order
5  2015-01-01         3    434.30  maltiple high value order
6  2015-01-01         1     58.73       single standard item
7  2015-01-01         3     74.99     maltiple standard item
8  2015-01-01         2    113.57  maltiple high value order
9  2015-01-01         1    499.45     single high value item

# **Using AND for Multiple Conditions**

In [ ]:
%%sql

select
  PERCENTILE_CONT(0.5) within group (order by netprice*quantity*exchangerate)

from sales
where
  orderdate between '2022-01-01' and '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   percentile_cont
0           398.00

In [ ]:
%%sql

with median_value as (
    select
      PERCENTILE_CONT(0.5) within group (order by s.netprice*s.quantity*s.exchangerate) as median

from sales s
where
  orderdate between '2022-01-01' and '2023-12-31'

)

select
  p.categoryname,
  sum(case when
     (s.netprice*s.quantity*s.exchangerate) <mv.median and S.orderdate between '2022-01-01' and '2022-12-31'
     then (s.netprice*s.quantity*s.exchangerate) else null end) as low_net_revenue_2022,

  sum(case when
     (s.netprice*s.quantity*s.exchangerate) >= mv.median AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
      then (s.netprice*s.quantity*s.exchangerate) else null end) as high_net_revenue_2022,

  sum(case when
      (s.netprice*s.quantity*s.exchangerate)<mv.median and orderdate between '2023-01-01' and '2023-12-31'
      then (s.netprice*s.quantity*s.exchangerate) else null end) as low_net_rev_2023



  from sales s
left join product p on s.productkey = p.productkey,
median_value mv
group by
  categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,low_net_revenue_2022,high_net_revenue_2022,low_net_rev_2023
0,Audio,222337.83,544600.39,180251.13
1,Cell phones,814449.53,7305215.55,729699.39
2,Cameras and camcorders,133004.54,2249528.02,104869.46
3,TV and Video,272338.29,5542998.32,164275.35
4,Home Appliances,219797.07,6392649.61,176261.35
5,Games and Toys,231979.63,84147.67,206103.36
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76
7,Computers,624340.42,17237873.07,590790.31

# **Multiple WHEN clauses in CASE** *Segmenting orders by percentiles*

In [ ]:
%%sql

select
      PERCENTILE_CONT(0.25) within group (order by s.netprice*s.quantity*s.exchangerate) as rev_25th_percentile,
      PERCENTILE_CONT(0.75) within group (order by s.netprice*s.quantity*s.exchangerate) as rev_75th_percentile

from sales s
where
  orderdate between '2022-01-01' and '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   rev_25th_percentile  rev_75th_percentile
0               111.07              1062.12

In [ ]:
%%sql

with percntile as (
select
      PERCENTILE_CONT(0.25) within group (order by s.netprice*s.quantity*s.exchangerate) as rev_25th_percentile,
      PERCENTILE_CONT(0.75) within group (order by s.netprice*s.quantity*s.exchangerate) as rev_75th_percentile

from sales s
where
  orderdate between '2022-01-01' and '2023-12-31'
)

select
  p.categoryname,
  case
    when (s.netprice*s.quantity*s.exchangerate) <=percntile.rev_25th_percentile then '3 - low'
    when (s.netprice*s.quantity*s.exchangerate) >=percntile.rev_75th_percentile then '1 - high'
    else '2 - medium'
    end as revenue_tier,
  SUM(s.netprice*s.quantity*s.exchangerate) as total_revenue


from sales s
left join product p on s.productkey = p.productkey
cross join percntile

WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
group by
  p.categoryname,
  revenue_tier
order by
  p.categoryname,
  revenue_tier

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                     categoryname revenue_tier  total_revenue
0                           Audio     1 - high      453108.90
1                           Audio   2 - medium      952700.06
2                           Audio      3 - low       49819.44
3         Cameras and camcorders      1 - high     3414876.61
4         Cameras and camcorders    2 - medium      929414.28
5         Cameras and camcorders       3 - low       21787.96
6                     Cell phones     1 - high     8557888.89
7                     Cell phones   2 - medium     5357700.03
8                     Cell phones      3 - low      206223.79
9                       Computers     1 - high    24192945.36
10                      Computers   2 - medium     5205799.01
11                      Computers      3 - low      114336.32
12                 Games and Toys     1 - high       34626.00
13                 Games and Toys   2 - medium      361328.43
14                 Games and Toys      3 - low      190547.84
15                Home Appliances     1 - high    10851234.48
16                Home Appliances   2 - medium     1646682.77
17                Home Appliances      3 - low       34522.31
18  Music, Movies and Audio Books     1 - high     2074182.51
19  Music, Movies and Audio Books   2 - medium     2817359.30
20  Music, Movies and Audio Books      3 - low      278523.59
21                   TV and Video     1 - high     8406606.84
22                   TV and Video   2 - medium     1796291.43
23                   TV and Video      3 - low       24616.56

In [ ]:
%%sql
select *
from product
limit 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3

In [ ]:
%%sql
select *
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

# **Date & Time Formatting**

In [ ]:
%%sql

select
  DATE_TRUNC('month', orderdate)::date as order_month,
  sum(quantity * netprice * exchangerate) as net_revenue,
  count(DISTINCT customerkey) as total_unique_customers
from sales
group by order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_unique_customers
0    2015-01-01    384092.66                     200
1    2015-02-01    706374.12                     291
2    2015-03-01    332961.59                     139
3    2015-04-01    160767.00                      78
4    2015-05-01    548632.63                     236
..          ...          ...                     ...
107  2023-12-01   2928550.93                    1484
108  2024-01-01   2677498.55                    1340
109  2024-02-01   3542322.55                    1718
110  2024-03-01   1692854.89                     877
111  2024-04-01    483851.39                     246

[112 rows x 3 columns]

TO CHAR()

In [ ]:
%%sql

select
  TO_CHAR(orderdate, 'yyyy-mm') as order_month,
  sum(quantity * netprice * exchangerate) as net_revenue,
  count(DISTINCT customerkey) as total_unique_customers
from sales
group by order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_unique_customers
0       2015-01    384092.66                     200
1       2015-02    706374.12                     291
2       2015-03    332961.59                     139
3       2015-04    160767.00                      78
4       2015-05    548632.63                     236
..          ...          ...                     ...
107     2023-12   2928550.93                    1484
108     2024-01   2677498.55                    1340
109     2024-02   3542322.55                    1718
110     2024-03   1692854.89                     877
111     2024-04    483851.39                     246

[112 rows x 3 columns]

# **Date & Time Filtering**

In [ ]:
%%sql

select
  orderdate,
  DATE_PART('year', orderdate) as order_year,
  DATE_PART('month', orderdate) as order_month,
  DATE_PART('day', orderdate) as order_day
from sales
order by random()
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  order_year  order_month  order_day
0  2019-04-26     2019.00         4.00      26.00
1  2019-12-13     2019.00        12.00      13.00
2  2022-10-05     2022.00        10.00       5.00
3  2022-05-20     2022.00         5.00      20.00
4  2021-10-23     2021.00        10.00      23.00
5  2023-02-22     2023.00         2.00      22.00
6  2019-05-14     2019.00         5.00      14.00
7  2023-10-23     2023.00        10.00      23.00
8  2019-12-14     2019.00        12.00      14.00
9  2019-02-02     2019.00         2.00       2.00

In [ ]:
%%sql

select
  orderdate,
  extract(year from orderdate) as extracted_year,
  extract(month from orderdate) as extracted_month,
  extract(day from orderdate) as extracted_day
from sales
order by random()
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate extracted_year extracted_month extracted_day
0  2022-11-26           2022              11            26
1  2023-11-21           2023              11            21
2  2022-08-05           2022               8             5
3  2019-12-26           2019              12            26
4  2022-10-07           2022              10             7
5  2017-02-28           2017               2            28
6  2022-11-12           2022              11            12
7  2023-03-08           2023               3             8
8  2018-08-03           2018               8             3
9  2021-09-17           2021               9            17

In [ ]:
%%sql

select
  extract(year from orderdate) as net_rev_yearly,
  extract(month from orderdate) as net_rev_monthy,
  sum(quantity * netprice	* exchangerate)
from sales
group by
net_rev_yearly,
net_rev_monthy
order by
net_rev_yearly,
net_rev_monthy
limit 19

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

19 rows affected.

   net_rev_yearly net_rev_monthy        sum
0            2015              1  384092.66
1            2015              2  706374.12
2            2015              3  332961.59
3            2015              4  160767.00
4            2015              5  548632.63
5            2015              6  748563.97
6            2015              7  635376.13
7            2015              8  718538.62
8            2015              9  696805.68
9            2015             10  824891.22
10           2015             11  691133.67
11           2015             12  922842.19
12           2016              1  835484.26
13           2016              2 1248641.69
14           2016              3  652327.29
15           2016              4  388379.57
16           2016              5  822952.67
17           2016              6  947950.98
18           2016              7  757521.90

In [ ]:
%%sql

select CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-05-24

In [ ]:
%%sql

select now()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2026-05-24 18:14:20.337333+00:00

In [28]:
%%sql

select

  s.orderdate,
  p.categoryname,
  sum(quantity * netprice * exchangerate) AS net_revenue
from sales s
left join product p on s.productkey = p.productkey
where
  extract(year from orderdate)>=extract(year from CURRENT_DATE) - 5

GROUP BY
s.orderdate,
p.categoryname

ORDER BY
s.orderdate,
p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-01-01                          Audio      1206.67
1     2021-01-01        Cameras and camcorders       2228.75
2     2021-01-01                    Cell phones     10582.00
3     2021-01-01                      Computers     12718.95
4     2021-01-01                 Games and Toys       235.53
...          ...                            ...          ...
8952  2024-04-20                      Computers     58353.68
8953  2024-04-20                 Games and Toys      1744.30
8954  2024-04-20                Home Appliances      1562.04
8955  2024-04-20  Music, Movies and Audio Books      4949.43
8956  2024-04-20                   TV and Video      9841.91

[8957 rows x 3 columns]